/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import clases_varias.conectar;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wwwki
 */
public class jfCardex extends javax.swing.JFrame {
    conectar cc= new conectar();
    /**
     * Creates new form jfEntrada_Salida
     */
    public jfCardex() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/CyCo64.png")).getImage());
        jtbCardex.setAutoResizeMode(jtbCardex.AUTO_RESIZE_OFF);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCardex = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jbtnFiltrar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jtfDesde = new javax.swing.JFormattedTextField();
        jtfHasta = new javax.swing.JFormattedTextField();
        jrFechas = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jbtnFiltrar1 = new javax.swing.JButton();
        jbtnFiltrar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 40, 480));

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 50, 40));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.cyan);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tipo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 770, 10));

        jtbCardex.setFont(new java.awt.Font("Ebrima", 0, 16)); // NOI18N
        jtbCardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbCardex.setRowHeight(25);
        jScrollPane1.setViewportView(jtbCardex);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 770, 410));

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.cyan);
        jLabel2.setText("Cardex");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 30));

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 430, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1260, 10));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.cyan);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Codigo Producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 250, 20));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.cyan);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Marca:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 20));

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 430, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.cyan);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Linea / Modelo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 20));

        jComboBox3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 430, 30));

        jbtnFiltrar.setBackground(java.awt.Color.black);
        jbtnFiltrar.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jbtnFiltrar.setForeground(new java.awt.Color(232, 251, 244));
        jbtnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar32.png"))); // NOI18N
        jbtnFiltrar.setText("Imprimir");
        jbtnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 500, 150, 50));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 10));

        jtfDesde.setBackground(new java.awt.Color(0, 0, 0));
        jtfDesde.setBorder(null);
        jtfDesde.setForeground(new java.awt.Color(255, 255, 255));
        jtfDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d-MM-yyyy"))));
        jtfDesde.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jtfDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDesdeActionPerformed(evt);
            }
        });
        jPanel1.add(jtfDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, -1));

        jtfHasta.setBackground(new java.awt.Color(0, 0, 0));
        jtfHasta.setBorder(null);
        jtfHasta.setForeground(new java.awt.Color(255, 255, 255));
        jtfHasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d-MM-yyyy"))));
        jtfHasta.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jtfHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfHastaActionPerformed(evt);
            }
        });
        jPanel1.add(jtfHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 180, -1));

        jrFechas.setBackground(new java.awt.Color(0, 0, 0));
        jrFechas.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jrFechas.setForeground(java.awt.Color.cyan);
        jrFechas.setText("Fecha Desde:                              Fecha Hasta:");
        jrFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFechasActionPerformed(evt);
            }
        });
        jPanel1.add(jrFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.cyan);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nombre Producto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 20));

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 430, -1));

        jbtnFiltrar1.setBackground(java.awt.Color.black);
        jbtnFiltrar1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jbtnFiltrar1.setForeground(new java.awt.Color(232, 251, 244));
        jbtnFiltrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar132.png"))); // NOI18N
        jbtnFiltrar1.setText("Mostrar");
        jbtnFiltrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiltrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFiltrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 390, 50));

        jbtnFiltrar2.setBackground(java.awt.Color.black);
        jbtnFiltrar2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jbtnFiltrar2.setForeground(new java.awt.Color(232, 251, 244));
        jbtnFiltrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/excel132.png"))); // NOI18N
        jbtnFiltrar2.setText("Exportar");
        jbtnFiltrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiltrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFiltrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void mostrar(){
        try {
            String ssql;
            String sSerie;
            String sNoDoc;
            Connection cn= cc.conexion();
            DefaultTableModel cadx = new DefaultTableModel();
            cadx.addColumn("TIPO DOC.");
            cadx.addColumn("SERIE");
            cadx.addColumn("NO. DOC");
            cadx.addColumn("TIPO MOVIMIENTO");
            cadx.addColumn("PRODUCTO");
            cadx.addColumn("CANTIDAD");
            cadx.addColumn("FECHA MOV.");
            cadx.addColumn("SUCURSAL");
            cadx.addColumn("BODEGA");
            cadx.addColumn("OBSERVACIONES");
            cadx.addColumn("USUARIO");            
            jtbCardex.setModel(cadx);
            
            //tipo doc
            jtbCardex.getColumnModel().getColumn(0).setMaxWidth(150);
            jtbCardex.getColumnModel().getColumn(0).setMinWidth(150);
            jtbCardex.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(150);
            jtbCardex.getTableHeader().getColumnModel().getColumn(0).setMinWidth(150);
            
            //serie
            jtbCardex.getColumnModel().getColumn(1).setMaxWidth(120);
            jtbCardex.getColumnModel().getColumn(1).setMinWidth(120);
            jtbCardex.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(120);
            jtbCardex.getTableHeader().getColumnModel().getColumn(1).setMinWidth(120);
            
            
            //no doc
            jtbCardex.getColumnModel().getColumn(2).setMaxWidth(100);
            jtbCardex.getColumnModel().getColumn(2).setMinWidth(100);
            jtbCardex.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(100);
            jtbCardex.getTableHeader().getColumnModel().getColumn(2).setMinWidth(100);
            
            //tipo mov
            jtbCardex.getColumnModel().getColumn(3).setMaxWidth(300);
            jtbCardex.getColumnModel().getColumn(3).setMinWidth(300);
            jtbCardex.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(300);
            jtbCardex.getTableHeader().getColumnModel().getColumn(3).setMinWidth(300);
            
            //prod
            jtbCardex.getColumnModel().getColumn(4).setMaxWidth(350);
            jtbCardex.getColumnModel().getColumn(4).setMinWidth(350);
            jtbCardex.getTableHeader().getColumnModel().getColumn(4).setMaxWidth(350);
            jtbCardex.getTableHeader().getColumnModel().getColumn(4).setMinWidth(350);
            
            //cantidad
            jtbCardex.getColumnModel().getColumn(5).setMaxWidth(80);
            jtbCardex.getColumnModel().getColumn(5).setMinWidth(80);
            jtbCardex.getTableHeader().getColumnModel().getColumn(5).setMaxWidth(80);
            jtbCardex.getTableHeader().getColumnModel().getColumn(5).setMinWidth(80);
            
            //fecha mov
            jtbCardex.getColumnModel().getColumn(6).setMaxWidth(100);
            jtbCardex.getColumnModel().getColumn(6).setMinWidth(100);
            jtbCardex.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(100);
            jtbCardex.getTableHeader().getColumnModel().getColumn(6).setMinWidth(100);
            
            //sucursal
            jtbCardex.getColumnModel().getColumn(7).setMaxWidth(130);
            jtbCardex.getColumnModel().getColumn(7).setMinWidth(130);
            jtbCardex.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(130);
            jtbCardex.getTableHeader().getColumnModel().getColumn(7).setMinWidth(130);
            
            //bodega
            jtbCardex.getColumnModel().getColumn(8).setMaxWidth(130);
            jtbCardex.getColumnModel().getColumn(8).setMinWidth(130);
            jtbCardex.getTableHeader().getColumnModel().getColumn(8).setMaxWidth(130);
            jtbCardex.getTableHeader().getColumnModel().getColumn(8).setMinWidth(130);
            
            //observaciones
            jtbCardex.getColumnModel().getColumn(9).setMaxWidth(200);
            jtbCardex.getColumnModel().getColumn(9).setMinWidth(200);
            jtbCardex.getTableHeader().getColumnModel().getColumn(9).setMaxWidth(200);
            jtbCardex.getTableHeader().getColumnModel().getColumn(9).setMinWidth(200);
            
            //usuario
            jtbCardex.getColumnModel().getColumn(10).setMaxWidth(100);
            jtbCardex.getColumnModel().getColumn(10).setMinWidth(100);
            jtbCardex.getTableHeader().getColumnModel().getColumn(10).setMaxWidth(100);
            jtbCardex.getTableHeader().getColumnModel().getColumn(10).setMinWidth(100);
                        
            
            ssql = "";
            ssql = ssql + " select tipo.txt_descripcion,";
            ssql = ssql + " (select tfac.no_serie_doc from tventa tfac where tfac.id_doc =   ti.id_doc) as serie,";
            ssql = ssql + " case when ti.id_tipo_movi = 1 then ";
            ssql = ssql + " (select tfac.nro_compra from tcompra tfac where tfac.id_compra = ti.id_doc)";
            ssql = ssql + " else (select tfac.no_doc from tventa tfac where tfac.id_doc = ti.id_doc)";
            ssql = ssql + " end no_doc,";
            ssql = ssql + " move.txt_descripcion_movi, tpro.txt_descripcion, ti.cantidad, ti.fecha_movimiento,";
            ssql = ssql + " tsuc.txt_descripcion, tbod.txt_descripcion, ti.txt_obsercaciones, tusu.cod_usuario,";
            ssql = ssql + " tipo.id_tipo_doc, ti.id_doc";
            ssql = ssql + " from tinventario ti";
            ssql = ssql + " inner join ttipo_documento tipo on tipo.id_tipo_doc = ti.id_tipo_doc";
            ssql = ssql + " inner join tsucursal tsuc on tsuc.id_sucursal = ti.id_sucursal";
            ssql = ssql + " inner join tbodega tbod on tbod.id_bodega = ti.id_bodega";
            ssql = ssql + " inner join ttipomovimiento_inv move on move.id_movi = ti.id_tipo_movi";
            ssql = ssql + " inner join tproducto tpro on tpro.id_producto = ti.id_producto";
            ssql = ssql + " inner join tusuario tusu on tusu.id_usuario = ti.id_usuario";
            ssql = ssql + " where ti.id_inv <> 0";
            ssql = ssql + " order by ti.id_inv desc";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ssql);
            String datos[]  = new String[13];
            while(rs.next()){
                if(rs.getInt(12) == 4 && rs.getInt(13) == 4){
                    sSerie = " - ";
                    sNoDoc = " - ";                        
                }else{
                    sSerie = rs.getString(2);
                    sNoDoc = rs.getString(3);
                }
                
                
                datos[0] = rs.getString(1);
                datos[1] = sSerie;
                datos[2] = sNoDoc;
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);
                datos[10] = rs.getString(11);
                cadx.addRow(datos);            
            }
            jtbCardex.setModel(cadx);  
            rs.close();
            st.close();
            cn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar cardex en: "+e);
        }                                
    }
    
    
    
    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        Menu_principal mp = new Menu_principal();
//        int dialog = JOptionPane.YES_NO_OPTION;
//        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
//        if(result == 0){
            //Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            this.dispose();
            mp.setVisible(true);
            Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, mp);
//        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(null);
    }//GEN-LAST:event_lblSalirMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbtnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFiltrarActionPerformed

    private void jtfDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDesdeActionPerformed

    private void jtfHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfHastaActionPerformed

    private void jrFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFechasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrFechasActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jbtnFiltrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiltrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFiltrar1ActionPerformed

    private void jbtnFiltrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiltrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFiltrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCardex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtnFiltrar;
    private javax.swing.JButton jbtnFiltrar1;
    private javax.swing.JButton jbtnFiltrar2;
    private javax.swing.JRadioButton jrFechas;
    private javax.swing.JTable jtbCardex;
    private javax.swing.JFormattedTextField jtfDesde;
    private javax.swing.JFormattedTextField jtfHasta;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
