/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;
import java.awt.Color;
import javax.swing.JOptionPane;
import Animacion.Fade;
import static Formas.jfProductos.iProceso_prod;
import clases_varias.permisos;
import clases_varias.user_logged;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;

/**
 *
 * @author wwwki
 */
public class jfConfigura extends javax.swing.JFrame {
      
    /**
     * Creates new form jfConfigura
     */
    public jfConfigura() {
        initComponents();        
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/CyCo64.png")).getImage());
        this.setLocationRelativeTo(null);
        Iterator<user_logged> itrLogg = Menu_principal.user_memory.iterator();
        user_logged ul = itrLogg.next();     
        permisos pr = new permisos();      
        pr.idUsu = ul.getidUsy();
        pr.cargar_permisos(3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblProducto = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblParametro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblProve = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTraslado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Configuraciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar32.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 50, 40));

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 50, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 910, 40));

        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/productos128.png"))); // NOI18N
        lblProducto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblProductoMouseMoved(evt);
            }
        });
        lblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductoMouseExited(evt);
            }
        });
        jPanel1.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 170, 210));

        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clientes128.png"))); // NOI18N
        lblCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblClienteMouseMoved(evt);
            }
        });
        lblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClienteMouseExited(evt);
            }
        });
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 220));

        jLabel3.setBackground(new java.awt.Color(232, 251, 244));
        jLabel3.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 251, 244));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 90, 60));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 251, 244));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Productos");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 130, 70));

        lblInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inventario.png"))); // NOI18N
        lblInventario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblInventarioMouseMoved(evt);
            }
        });
        lblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInventarioMouseExited(evt);
            }
        });
        jPanel1.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 170, 220));

        jLabel6.setBackground(new java.awt.Color(232, 251, 244));
        jLabel6.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 251, 244));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inventario");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 130, 60));

        lblParametro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblParametro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/parametro.png"))); // NOI18N
        lblParametro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblParametroMouseMoved(evt);
            }
        });
        lblParametro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblParametroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblParametroMouseExited(evt);
            }
        });
        jPanel1.add(lblParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 180, 190));

        jLabel8.setBackground(new java.awt.Color(232, 251, 244));
        jLabel8.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 251, 244));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Parámetros");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 140, 40));

        lblCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/compras.png"))); // NOI18N
        lblCompras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblComprasMouseMoved(evt);
            }
        });
        lblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComprasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComprasMouseExited(evt);
            }
        });
        jPanel1.add(lblCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 160, 220));

        jLabel9.setBackground(new java.awt.Color(232, 251, 244));
        jLabel9.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 251, 244));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Compras");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 130, 60));

        jlblProve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblProve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedor.png"))); // NOI18N
        jlblProve.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlblProveMouseMoved(evt);
            }
        });
        jlblProve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblProveMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblProveMouseExited(evt);
            }
        });
        jPanel1.add(jlblProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 180, 220));

        jLabel10.setBackground(new java.awt.Color(232, 251, 244));
        jLabel10.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 251, 244));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Proveedores");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 130, 50));

        lblTraslado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTraslado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/traslado.png"))); // NOI18N
        lblTraslado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblTrasladoMouseMoved(evt);
            }
        });
        lblTraslado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrasladoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTrasladoMouseExited(evt);
            }
        });
        jPanel1.add(lblTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 170, 220));

        jLabel7.setBackground(new java.awt.Color(232, 251, 244));
        jLabel7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 251, 244));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Traslado");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
             
        Menu_principal mp = new Menu_principal();
//        int dialog = JOptionPane.YES_NO_OPTION;
//        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
//        if(result == 0){                                               
            //Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            this.dispose();
            mp.setVisible(true);
            Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, mp);  
//        }
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteMouseMoved
        lblCliente.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblClienteMouseMoved

    private void lblProductoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductoMouseMoved
        lblProducto.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblProductoMouseMoved

    private void lblProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductoMouseExited
        lblProducto.setBorder(null);
    }//GEN-LAST:event_lblProductoMouseExited

    private void lblClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteMouseExited
        lblCliente.setBorder(null);
    }//GEN-LAST:event_lblClienteMouseExited

    private void lblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductoMouseClicked
        if(lblProducto.isEnabled()){
            jfProductos pro = new jfProductos();                
            pro.iProceso_prod = 1;
            pro.setVisible(true);
            this.dispose();
            Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, pro);  
        }               
    }//GEN-LAST:event_lblProductoMouseClicked

    private void lblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClienteMouseClicked
        if(lblCliente.isEnabled()){
            jfCliente cli = new jfCliente();            
            cli.iTipoProc = 1;
            this.dispose();
            cli.setVisible(true);
            Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, cli);  
        }
        
        
    }//GEN-LAST:event_lblClienteMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblInventarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseMoved
        lblInventario.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblInventarioMouseMoved

    private void lblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseClicked
        if(lblInventario.isEnabled()){
            jfInventario sr = new jfInventario();            
    //        sr.iProceso = 1;
            this.dispose();
            sr.setVisible(true);
            Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, sr);  
        }
        
    }//GEN-LAST:event_lblInventarioMouseClicked

    private void lblInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventarioMouseExited
        lblInventario.setBorder(null);
    }//GEN-LAST:event_lblInventarioMouseExited

    private void lblParametroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametroMouseMoved
        lblParametro.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblParametroMouseMoved

    private void lblParametroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametroMouseClicked

        try {
            if(lblParametro.isEnabled()){
                jfParametros para = new jfParametros();                
                this.dispose();
                para.setVisible(true);                
            }            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblParametroMouseClicked

    private void lblParametroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblParametroMouseExited
        lblParametro.setBorder(null);
    }//GEN-LAST:event_lblParametroMouseExited

    private void lblComprasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprasMouseMoved
         lblCompras.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblComprasMouseMoved

    private void lblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprasMouseClicked

        try {
            if(lblCompras.isEnabled()){
                jfListadoCompras lc = new jfListadoCompras();                
                lc.setVisible(true);
                this.dispose();            
            }           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblComprasMouseClicked

    private void lblComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprasMouseExited
        lblCompras.setBorder(null);
    }//GEN-LAST:event_lblComprasMouseExited

    private void jlblProveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProveMouseClicked

        try {
            if(jlblProve.isEnabled()){
                jfProveedor prove = new jfProveedor();
                prove.setVisible(true);
                this.dispose();        
            }            
        } catch (Exception e) {
        }

       
    }//GEN-LAST:event_jlblProveMouseClicked

    private void jlblProveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProveMouseMoved
        jlblProve.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_jlblProveMouseMoved

    private void jlblProveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblProveMouseExited
        jlblProve.setBorder(null);
    }//GEN-LAST:event_jlblProveMouseExited

    private void lblTrasladoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrasladoMouseMoved
        lblTraslado.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblTrasladoMouseMoved

    private void lblTrasladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrasladoMouseClicked
        if(lblTraslado.isEnabled()){
            jfListadoTraslado lt = new jfListadoTraslado();
            lt.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblTrasladoMouseClicked

    private void lblTrasladoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrasladoMouseExited
        lblTraslado.setBorder(null);
    }//GEN-LAST:event_lblTrasladoMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfConfigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfConfigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfConfigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfConfigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfConfigura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel jlblProve;
    public static javax.swing.JLabel lblCliente;
    public static javax.swing.JLabel lblCompras;
    public static javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblMinimizar;
    public static javax.swing.JLabel lblParametro;
    public static javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSalir;
    public static javax.swing.JLabel lblTraslado;
    // End of variables declaration//GEN-END:variables
}
