/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;
import java.awt.Color;
import javax.swing.JOptionPane;
import Animacion.Fade;
import static Formas.Menu_principal.user_memory;
import static Formas.jfProductos.iProceso_prod;
import clases_varias.permisos;
import clases_varias.user_logged;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;

/**
 *
 * @author wwwki
 */
public class jfParametros extends javax.swing.JFrame {    
    /**
     * Creates new form jfConfigura
     */
    public jfParametros() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/bender_cyco.png")).getImage());
        this.setLocationRelativeTo(null);
        Iterator<user_logged> itrLogg  = Menu_principal.user_memory.iterator();
        user_logged ul = itrLogg.next();     
        permisos pr = new permisos();      
        pr.idUsu = ul.getidUsy();
        pr.cargar_permisos(4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSucursal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSeries = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSeries_recibo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBodega = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPermisos = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("Parámetros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar32.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 50, 40));

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPanel1.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 50, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 890, 40));

        lblSucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sucursal.png"))); // NOI18N
        lblSucursal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSucursalMouseMoved(evt);
            }
        });
        lblSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSucursalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSucursalMouseExited(evt);
            }
        });
        jPanel1.add(lblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, 220));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sucursal");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 130, 70));

        lblSeries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/serie_factura.png"))); // NOI18N
        lblSeries.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSeriesMouseMoved(evt);
            }
        });
        lblSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeriesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSeriesMouseExited(evt);
            }
        });
        jPanel1.add(lblSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 170, 220));

        jLabel4.setBackground(new java.awt.Color(232, 251, 244));
        jLabel4.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Serie Factura");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 170, 60));

        lblSeries_recibo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeries_recibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/serie_recibo.png"))); // NOI18N
        lblSeries_recibo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSeries_reciboMouseMoved(evt);
            }
        });
        lblSeries_recibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeries_reciboMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSeries_reciboMouseExited(evt);
            }
        });
        jPanel1.add(lblSeries_recibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, 220));

        jLabel7.setBackground(new java.awt.Color(232, 251, 244));
        jLabel7.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Serie Recibo");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, 60));

        lblBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bodega.png"))); // NOI18N
        lblBodega.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblBodegaMouseMoved(evt);
            }
        });
        lblBodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBodegaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBodegaMouseExited(evt);
            }
        });
        jPanel1.add(lblBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 170, 210));

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bodega");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 130, 70));

        lblMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/marca.png"))); // NOI18N
        lblMarca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMarcaMouseMoved(evt);
            }
        });
        lblMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMarcaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMarcaMouseExited(evt);
            }
        });
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, 210));

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Marca");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 120, 60));

        lblModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modelo.png"))); // NOI18N
        lblModelo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblModeloMouseMoved(evt);
            }
        });
        lblModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModeloMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModeloMouseExited(evt);
            }
        });
        jPanel1.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 170, 210));

        jLabel12.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Modelo");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 130, 60));

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user.png"))); // NOI18N
        lblUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblUserMouseMoved(evt);
            }
        });
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 170, 210));

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Usuario");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 130, 60));

        lblPermisos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/permisos_usu.png"))); // NOI18N
        lblPermisos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblPermisosMouseMoved(evt);
            }
        });
        lblPermisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPermisosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPermisosMouseExited(evt);
            }
        });
        jPanel1.add(lblPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 170, 210));

        jLabel14.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("<html><p align=\"center\">Permisos<br>Usuario<p></html>\n");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 130, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        jfConfigura conf = new jfConfigura();         
        conf.setVisible(true);
        Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, conf);  
        this.dispose();
        
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblSucursalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSucursalMouseMoved
        lblSucursal.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblSucursalMouseMoved

    private void lblSucursalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSucursalMouseExited
        lblSucursal.setBorder(null);
    }//GEN-LAST:event_lblSucursalMouseExited

    private void lblSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSucursalMouseClicked
        if(lblSucursal.isEnabled()){
            jfSucursal suc = new jfSucursal();                       
            suc.setVisible(true);
            this.dispose();
        }                        
    }//GEN-LAST:event_lblSucursalMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(41,42,44)));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblSeriesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeriesMouseMoved
         lblSeries.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblSeriesMouseMoved

    private void lblSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeriesMouseClicked
        if(lblSeries.isEnabled()){
            jfSeries sr = new jfSeries();
            sr.iProceso = 1;            
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            sr.setVisible(true);                
        }        
    }//GEN-LAST:event_lblSeriesMouseClicked

    private void lblSeriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeriesMouseExited
        lblSeries.setBorder(null);
    }//GEN-LAST:event_lblSeriesMouseExited

    private void lblSeries_reciboMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeries_reciboMouseMoved
        lblSeries_recibo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblSeries_reciboMouseMoved

    private void lblSeries_reciboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeries_reciboMouseClicked
        if(lblSeries_recibo.isEnabled()){
            jfSeries_recibo sr = new jfSeries_recibo();
            sr.iProceso = 1;
            sr.setVisible(true);
            this.dispose();        
        }                        
    }//GEN-LAST:event_lblSeries_reciboMouseClicked

    private void lblSeries_reciboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeries_reciboMouseExited
         lblSeries_recibo.setBorder(null);
    }//GEN-LAST:event_lblSeries_reciboMouseExited

    private void lblBodegaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBodegaMouseMoved
        lblBodega.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblBodegaMouseMoved

    private void lblBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBodegaMouseClicked
        if(lblBodega.isEnabled()){
            jfBodega bg = new jfBodega();            
            bg.setVisible(true);
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
        }        
    }//GEN-LAST:event_lblBodegaMouseClicked

    private void lblBodegaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBodegaMouseExited
        lblBodega.setBorder(null);
    }//GEN-LAST:event_lblBodegaMouseExited

    private void lblMarcaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcaMouseMoved
        lblMarca.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblMarcaMouseMoved

    private void lblMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcaMouseClicked
        if(lblMarca.isEnabled()){
            jfMarca marca = new jfMarca();            
            marca.setVisible(true);
            this.dispose();
        }                
    }//GEN-LAST:event_lblMarcaMouseClicked

    private void lblMarcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcaMouseExited
            lblMarca.setBorder(null);
    }//GEN-LAST:event_lblMarcaMouseExited

    private void lblModeloMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModeloMouseMoved
        lblModelo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblModeloMouseMoved

    private void lblModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModeloMouseClicked
        if(lblModelo.isEnabled()){
            jfModelo mod = new jfModelo();            
            mod.setVisible(true);
            this.dispose();
        }        
    }//GEN-LAST:event_lblModeloMouseClicked

    private void lblModeloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModeloMouseExited
        lblModelo.setBorder(null);
    }//GEN-LAST:event_lblModeloMouseExited

    private void lblUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseMoved
        lblUser.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblUserMouseMoved

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        jfUsuario usu = new jfUsuario();        
        usu.setVisible(true);
        usu.iProceso = 1;
        this.dispose();
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        lblUser.setBorder(null);
    }//GEN-LAST:event_lblUserMouseExited

    private void lblPermisosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermisosMouseMoved
        lblPermisos.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblPermisosMouseMoved

    private void lblPermisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermisosMouseClicked
        jfPermisos per = new jfPermisos();        
        per.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPermisosMouseClicked

    private void lblPermisosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPermisosMouseExited
        lblPermisos.setBorder(null);
    }//GEN-LAST:event_lblPermisosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfParametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lblBodega;
    public static javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMinimizar;
    public static javax.swing.JLabel lblModelo;
    public static javax.swing.JLabel lblPermisos;
    private javax.swing.JLabel lblSalir;
    public static javax.swing.JLabel lblSeries;
    public static javax.swing.JLabel lblSeries_recibo;
    public static javax.swing.JLabel lblSucursal;
    public static javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
