/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.*;
import clases_varias.conectar;
import clases_varias.user_logged;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;


/**
 *
 * @author wwwki
 */
public class Login extends javax.swing.JFrame {        
        conectar cc= new conectar();     
        public static ArrayList<user_logged> user_logg = new ArrayList<user_logged>();
//        ArrayList<user_logged> user_logg = new ArrayList<user_logged>();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/CyCo64.png")).getImage());
        this.setLocationRelativeTo(null);   
        user_logg.clear();
    }
    
    
    void validarIngreso(String sUsuario, String sPass){
    String ssql;   
        try {
            Connection cn= cc.conexion();            
            ssql = "";
            ssql = ssql + "select * from tusuario ";
            ssql = ssql + " where cod_usuario = " + "'" +sUsuario.toUpperCase()+"'";
            ssql = ssql + " and pass_usuario =" + "'" +sPass+ "'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ssql);
             if(rs.next()){                 
                ssql = "";
                ssql = ssql + "select * from tusuario ";
                ssql = ssql + " where cod_usuario = " + "'" +sUsuario.toUpperCase()+"'";
                ssql = ssql + " and pass_usuario =" + "'" +sPass+ "'";
                ssql = ssql + " and sn_activo = 1";
                Statement stt = cn.createStatement();
                ResultSet rss = stt.executeQuery(ssql);
                if (rss.next()){                                                                                                 
                    user_logged ulo = new user_logged();
                    ulo.setUsy(rs.getString("txt_nombre_usu"));
                    ulo.setidUsu(rs.getInt("id_usuario"));    
                    user_logg.add(ulo);                                                                                
//                    Iterator<user_logged> itrLogg = user_logg.iterator();
//                    user_logged ul = itrLogg.next();
//                    JOptionPane.showMessageDialog(null, ul.getUsy() + " - " + ul.getidUsy() );                    
                    JOptionPane.showMessageDialog(null, "Bienvenido: "+ ulo.getUsy(),"CyCo",JOptionPane.INFORMATION_MESSAGE );
                    Menu_principal.user_memory = (ArrayList)user_logg.clone();
                    Menu_principal mp = new Menu_principal();                                                                                
                    mp.setVisible(true);                                                     
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "El usuario ingresado esta dado de baja, no puede ingresar","CyCo",JOptionPane.INFORMATION_MESSAGE );
                }  
                rss.close();
                stt.close();
            }else{
               JOptionPane.showMessageDialog(null, "Usuario o contraseña no coiciden ","INGRESRO",JOptionPane.INFORMATION_MESSAGE );
             }  
             rs.close();
             st.close();
             cn.close();
        } catch (Exception e ) {
//        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al validar:" + e,"Ingreso",JOptionPane.ERROR_MESSAGE );
        }              
    }
                                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();
        lblFacebook = new javax.swing.JLabel();
        lblTwitter = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jpMaxMin = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setBackground(new java.awt.Color(0, 0, 0));
        jpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CyCo156.png"))); // NOI18N
        jpLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 110));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        jpLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txt_usuario.setBackground(new java.awt.Color(0, 0, 0));
        txt_usuario.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(0, 255, 255));
        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_usuario.setText("Ingrese Usuario");
        txt_usuario.setBorder(null);
        txt_usuario.setSelectedTextColor(java.awt.Color.green);
        txt_usuario.setSelectionColor(new java.awt.Color(9, 10, 11));
        txt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usuarioFocusGained(evt);
            }
        });
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        jpLogin.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        jpLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, 10));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        jpLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));
        jpLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 240, 10));

        txt_pass.setBackground(new java.awt.Color(0, 0, 0));
        txt_pass.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txt_pass.setForeground(java.awt.Color.cyan);
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_pass.setText("Contraseña");
        txt_pass.setBorder(null);
        txt_pass.setSelectedTextColor(java.awt.Color.green);
        txt_pass.setSelectionColor(new java.awt.Color(9, 10, 11));
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jpLogin.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 200, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/login_32px.png"))); // NOI18N
        jpLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        lblWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mapas-y-banderas.png"))); // NOI18N
        jpLogin.add(lblWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 40, 30));

        lblFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/facebook.png"))); // NOI18N
        lblFacebook.setText("jLabel9");
        jpLogin.add(lblFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 40, 40, 40));

        lblTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gorjeo.png"))); // NOI18N
        jpLogin.add(lblTwitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 80, 40, 40));

        btnIngresar.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresar.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        btnIngresar.setForeground(java.awt.Color.cyan);
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.setOpaque(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jpLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, 40));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pregunta.png"))); // NOI18N
        jLabel8.setText("Ayuda");
        jpLogin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, -1));

        getContentPane().add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 480));

        jpMaxMin.setBackground(java.awt.Color.black);
        jpMaxMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        lblExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblExitMouseMoved(evt);
            }
        });
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jpMaxMin.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jpMaxMin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        getContentPane().add(jpMaxMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0){
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);
        }        
    }//GEN-LAST:event_lblExitMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
                      
        if(lblWeb.getX() == -30){
            //Mostrar
            Animacion.mover_derecha(-30, 10, 10, 5, lblWeb);
            Animacion.mover_derecha(-30, 10, 10, 5, lblFacebook);
            Animacion.mover_derecha(-30, 10, 10, 5, lblTwitter);
        }
        if(lblWeb.getX() == 10){
            //Ocultar
            Animacion.mover_izquierda(10, -30, 10, 5, lblWeb);
            Animacion.mover_izquierda(10, -30, 10, 5, lblFacebook);
            Animacion.mover_izquierda(10, -30, 10, 5, lblTwitter);
        }                            
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        char[] cPass = txt_pass.getPassword();
        String sPass = new String(cPass);
        validarIngreso(txt_usuario.getText(),sPass);                                                                
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usuarioFocusGained
        txt_usuario.selectAll();
    }//GEN-LAST:event_txt_usuarioFocusGained

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
       txt_pass.selectAll();
    }//GEN-LAST:event_txt_passFocusGained

    private void lblExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseMoved
        lblExit.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblExitMouseMoved

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setBorder(null);
    }//GEN-LAST:event_lblExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpMaxMin;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFacebook;
    private javax.swing.JLabel lblTwitter;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
