/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas;

import Animacion.Fade;
import clases_varias.permisos;
import clases_varias.user_logged;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwki
 */
public class Menu_principal extends javax.swing.JFrame {        
    public static ArrayList<user_logged> user_memory = new ArrayList<user_logged>();   
    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();        
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/CyCo64.png")).getImage());
        this.setLocationRelativeTo(null);
//        Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, this);    
        Iterator<user_logged> itrLogg  = user_memory.iterator();
        user_logged ul = itrLogg.next();     
        permisos pr = new permisos();      
        pr.idUsu = ul.getidUsy();
        pr.cargar_permisos(1);
//        
//        Iterator<user_logged> itrLogg = user_memory.iterator();
//        user_logged ul = itrLogg.next();                                      
//        JOptionPane.showMessageDialog(null, "El usuario es: " + ul.getUsy() + "\n" + ul.getidUsy());  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jsMenu = new javax.swing.JSeparator();
        lblMenu = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblFacturar = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblConfigura = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMenu1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(java.awt.Color.black);
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsMenu.setBackground(new java.awt.Color(232, 251, 244));
        jsMenu.setForeground(java.awt.Color.cyan);
        jpMenu.add(jsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1030, 10));

        lblMenu.setBackground(new java.awt.Color(41, 42, 44));
        lblMenu.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(232, 251, 244));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CyCo128.png"))); // NOI18N
        jpMenu.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, -1));

        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar32.png"))); // NOI18N
        lblSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirMouseMoved(evt);
            }
        });
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jpMenu.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 50, 40));

        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar32.png"))); // NOI18N
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jpMenu.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 40));

        lblFacturar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono-factura.png"))); // NOI18N
        lblFacturar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblFacturarMouseMoved(evt);
            }
        });
        lblFacturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacturarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFacturarMouseExited(evt);
            }
        });
        jpMenu.add(lblFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 330, 330));

        lblReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reportes2128.png"))); // NOI18N
        lblReportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblReportesMouseMoved(evt);
            }
        });
        lblReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportesMouseExited(evt);
            }
        });
        jpMenu.add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 200, 210));

        lblConfigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfigura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/configuracion128.png"))); // NOI18N
        lblConfigura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblConfiguraMouseMoved(evt);
            }
        });
        lblConfigura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfiguraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfiguraMouseExited(evt);
            }
        });
        jpMenu.add(lblConfigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 200, 200));

        jLabel7.setBackground(new java.awt.Color(41, 42, 44));
        jLabel7.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 251, 244));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Configuraciones");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpMenu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 60));

        jLabel8.setBackground(new java.awt.Color(41, 42, 44));
        jLabel8.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 251, 244));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Facturar");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 210, 60));

        jLabel9.setBackground(new java.awt.Color(41, 42, 44));
        jLabel9.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 251, 244));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reportes");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 100, 60));

        lblMenu1.setBackground(new java.awt.Color(41, 42, 44));
        lblMenu1.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblMenu1.setForeground(java.awt.Color.cyan);
        lblMenu1.setText("Menu Principal");
        jpMenu.add(lblMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseMoved
                lblSalir.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
    }//GEN-LAST:event_lblSalirMouseMoved

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?","Salir",dialog);
        if(result == 0){
            Login lg = new Login();            
            //Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            Menu_principal.user_memory.clear();
            lg.setVisible(true);
        }        
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblFacturarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturarMouseExited
        //lblFacturar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        lblFacturar.setBorder(null);
    }//GEN-LAST:event_lblFacturarMouseExited

    private void lblFacturarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturarMouseMoved
        
        lblFacturar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblFacturarMouseMoved

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        lblSalir.setBorder(null);
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblConfiguraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguraMouseMoved
        lblConfigura.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblConfiguraMouseMoved

    private void lblConfiguraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguraMouseExited
        lblConfigura.setBorder(null);
    }//GEN-LAST:event_lblConfiguraMouseExited

    private void lblReportesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseMoved
        lblReportes.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblReportesMouseMoved

    private void lblReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseExited
        lblReportes.setBorder(null);
    }//GEN-LAST:event_lblReportesMouseExited

    private void lblFacturarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturarMouseClicked
        
        //Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.EXIT);
        //FrmMenu mn = new FrmMenu();      
        //Login lg = new Login();
        //this.dispose();
        //mn.setVisible(true);        
        //Fade.JFrameFadeIn(0f, 1f, 0.1f,50, mn);
        
        if(lblFacturar.isEnabled()){
            jfFacturar fc = new jfFacturar();   
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            //this.dispose();                   
            fc.setVisible(true);
        }                
        //Fade.JFrameFadeIn(0f, 1f, 0.2f, 50, fc);                                                         
    }//GEN-LAST:event_lblFacturarMouseClicked

    private void lblConfiguraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguraMouseClicked
        if(lblConfigura.isEnabled()){
            jfConfigura confi = new jfConfigura();                          
            confi.setVisible(true);
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
        }              
    }//GEN-LAST:event_lblConfiguraMouseClicked

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        lblMinimizar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.CYAN));
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
          lblMinimizar.setBorder(null);
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportesMouseClicked
        if(lblReportes.isEnabled()){                    
            jfReportes fc = new jfReportes();               
            Fade.JFrameFadeOut(1f, 0f, 0.1f, 50, this,Fade.DISPOSE);
            //this.dispose();       
            fc.setVisible(true);
        }       
    }//GEN-LAST:event_lblReportesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JSeparator jsMenu;
    public static javax.swing.JLabel lblConfigura;
    public static javax.swing.JLabel lblFacturar;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblMinimizar;
    public static javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblSalir;
    // End of variables declaration//GEN-END:variables
}
